version: '3.8'

services:
  db: 
    image: mysql:8.0
    container_name: mysql8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab-bd
      MYSQL_PASSWORD: password123
      MYSQL_USER: user
    volumes:
      - ./mysql:/var/lib/mysql
    